---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Insert title of project here"
subtitle: "https://github.com/rml41/EDA_2020_Project.git"
author: "Rachel Landman"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
setwd("/Users/rmlandman/Desktop/Data Analytics/Environmental_Data_Analytics_2020/Project/EDA_2020_Project")

getwd()

# Load your packages

library(tidyverse)
library(plyr)
library(dataRetrieval)
library(ggplot2)
library(cowplot)
library(lubridate)

# Set your ggplot theme

mytheme <- theme_bw(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")

theme_set(mytheme)


# Load your datasets

```


# Rationale and Research Questions

Ellerbe Creek runs into the Falls Lake Resovoir, through the city of Durham, North Carolina. Falls Lake serves as the source of drinking water for the City of Raleigh and does not meet North Carolina standards for *chlorophyll a*, which is found in algae (SOURCE: https://durhamnc.gov/716/Falls-Lake). Algal blooms generally come from excess nutrients such as phosphorus and nitrogen. Ellerbe Creek is one of the sources of excess nutrients and contaminents in Falls Lake. The Ellerbe Creek Watershed has the highest population density of Durham's watersheds, with an estimated 22% impervious surface (SOURCE: https://files.nc.gov/ncdeq/Water%20Quality/Planning/BPU/BPU/Neuse/Neuse%20Plans/2009%20Plan/Chapter%201.pdf). It is impacted by both point and nonpoint sources and was found to deliver the highest nutrient loads to Falls Lake (SOURCE: https://files.nc.gov/ncdeq/Water%20Quality/Planning/BPU/BPU/Neuse/Neuse%20Plans/2009%20Plan/Chapter%201.pdf). Ellerbe Creek and Falls Lake are both on the state's impaired water bodies list (303(d) list) (SOURCE https://durhamnc.gov/711/Ellerbe-Creek-Watershed, https://www.usgs.gov/centers/sa-water/science/groundwatersurface-water-interaction-near-ellerbe-creek-durham-nc?qt-science_center_objects=0#qt-science_center_objects). Ellerbe Creek was first listed on the 303(d) list in 1998 (SOURCE: https://files.nc.gov/ncdeq/Water%20Quality/Planning/BPU/BPU/Neuse/Neuse%20Plans/2009%20Plan/Chapter%201.pdf)

This analysis and report will aim to answer the following questions: 
1. What are the overall Nitrogen and Phosphorus levels in Ellerbe Creek?
2. Is there a relationship between flow and Nitrogen or Phosphorus levels?
3. How does location, upstream vs. downstream, impact nutrient levels? 

\newpage

# Dataset Information

Nutrient data for this project were downloaded from the the Water Quality Portal, a coorperative service sponsered by the United States Geological Survey (USGS), the Environmental Protection Agency (EPA), and the National Water Quality Monitoring Council (NWQMC) on February 27, 2020. Discharge data were downloaded for two stream gages along Ellerbe Creek, HUC code 030202010403, from USGS using the data dataRetrieval package in R. The dataset analyzed contains 21 monitoring locations with measurments for nitrogen and phosphorus levels from 1982 to 2018 and daily discharge data from 2008 to 20202. Not all locations had data for each nutrient. Nitrogen and Phosphorus concentrations are recorded as mg/L of Nitrogen or Phosphorus in various compounds including, nitrate, nitrite, ammonia, ammonium, organic nitrogen, phosphate, and organic phosphorus. The USGS gage locations are Club Blvd (0208675010), upstream, and Gorman (02086849), downstream. 

Variable| Units | Range | Mean | Median| Source
--------------|-----|--------------|---------|---------|----------
Nitrogen| mg/L N| 0.37 - 33.00 | 7.18 | 2.82| NC DENR and USGS
Phosphorus | mg/L P| 0.039 - 17.00 | 1.091 | 0.157 | NC DENR and USGS
Discarge Club | ft^3/s | 0.20 - 781.00 | 9.39 | 1.28 | USGS
Discharge Gorman | ft^3/s | 7.52 - 1750.00 | 48.84 | 20.50 | USGS


\newpage

# Exploratory Analysis 

## Initial Exploration 

Explored raw data from the water quality portal to determine potential variables for analysis and time period of data. Selected Nitrogen and Phosphorus as the two variables to analyze. Explore discharge data to determine date range of data.  

## Discharge Data Wrangling 

Flow data from the two USGS stream gages were combined in two data sets, one as a long format with all discharge in one column and one in wide format, with two seperate columns for discharge based on location. 

## Nutrient Data Wrangling 

The nutrient data set from the water quality portal was cleans to remove all irrelevant information and retain just characterstics of interest, Nitrogen and Phosphorus. Nitrogen and Phosphorus values for many samples were recorded as both mg/L of N and P, and of NO3 and PO4 respectively. Data were downloaded in long format and were converted to wide format in order to convert Nitrogen and Phosphorus values to mg/L of N or P. 

\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
