---
title: "Project_DataExploration"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Set Working Directory and Load Data 
```{r setup, include=FALSE}
# Set your working directory

setwd("/Users/rmlandman/Desktop/Data Analytics/Environmental_Data_Analytics_2020/Project/EDA_2020_Project")
getwd()

# Load your packages


library(plyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(viridis)
library(RColorBrewer)
library(cowplot)

# Set your ggplot theme

mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")

theme_set(mytheme)

# Load your datasets

EC_Flow.Nutrients_Wide <-
  read.csv("./Data/Processed/EC_Flow.Nutrients_Wide_Processed.csv")

Club.Gorman_Flow.Nutrients_Wide <-
  read.csv("./Data/Processed/ClubGorman_Flow.Nutrients_Wide_Processed.csv")

Club.Gorman_Flow_Long <- read.csv("./Data/Processed/ClubGorman_USGSDischarge_Long.csv")

class(Club.Gorman_Flow_Long$X_00060_00003)

Club.Gorman_Flow_Wide <- read.csv("./Data/Processed/ClubGorman_USGSDischarge_Wide.csv")

Club.Gorman_Flow.Nutrients_Long <-
  read.csv("./Data/Processed/ClubGorman_Flow.Nutrients_Long_Processed.csv")

```

# Format Dates
```{r}
Club.Gorman_Flow.Nutrients_Wide$Date <- 
  as.Date(Club.Gorman_Flow.Nutrients_Wide$Date, format = "%Y-%m-%d")
class(Club.Gorman_Flow.Nutrients_Wide$Date)

Club.Gorman_Flow_Wide$Date <- 
  as.Date(Club.Gorman_Flow_Wide$Date, format = "%Y-%m-%d")
class(Club.Gorman_Flow_Wide$Date)

Club.Gorman_Flow_Long$Date <- 
  as.Date(Club.Gorman_Flow_Long$Date, format = "%Y-%m-%d")
class(Club.Gorman_Flow_Long$Date)

EC_Flow.Nutrients_Wide$Date <- 
  as.Date(EC_Flow.Nutrients_Wide$Date, format = "%Y-%m-%d")
class(EC_Flow.Nutrients_Wide$Date)

Club.Gorman_Flow.Nutrients_Long$Date <-
  as.Date(Club.Gorman_Flow.Nutrients_Long$Date, format = "%Y-%m-%d")
class(Club.Gorman_Flow.Nutrients_Long$Date)


```

#Format Site Number to Character
```{r}

Club.Gorman_Flow.Nutrients_Wide$site_no <- 
  as.character(Club.Gorman_Flow.Nutrients_Wide$site_no)
class(Club.Gorman_Flow.Nutrients_Wide$site_no)

Club.Gorman_Flow_Wide$site_no.x <- 
  as.character(Club.Gorman_Flow_Wide$site_no.x)
class(Club.Gorman_Flow_Wide$site_no.x)

Club.Gorman_Flow_Wide$site_no.y <- 
  as.character(Club.Gorman_Flow_Wide$site_no.y)
class(Club.Gorman_Flow_Wide$site_no.y)

Club.Gorman_Flow_Long$site_no <- 
  as.character(Club.Gorman_Flow_Long$site_no, format)
class(Club.Gorman_Flow_Long$site_no)

EC_Flow.Nutrients_Wide$site_no <- 
  as.character(EC_Flow.Nutrients_Wide$site_no)
class(EC_Flow.Nutrients_Wide$site_no)

EC_Flow.Nutrients_Wide$site_no.x <- 
  as.character(EC_Flow.Nutrients_Wide$site_no.x)
class(EC_Flow.Nutrients_Wide$site_no.x)

EC_Flow.Nutrients_Wide$site_no.y <- 
  as.character(EC_Flow.Nutrients_Wide$site_no.y)
class(EC_Flow.Nutrients_Wide$site_no.y)

```


# Find Start and End dates 
# find out the start and end dates of the dataset
```{r}
#Date range for flow 
interval(first(Club.Gorman_Flow_Long$Date), last(Club.Gorman_Flow_Long$Date))

```

# Flow Summaries             
```{r}
Club.Gorman_Flow_MonthSummary <- Club.Gorman_Flow_Long %>% 
  mutate(month = month(Date, label = TRUE)) %>% 
  group_by(site_no, month) %>% 
  filter(!is.na(Discharge)) %>% 
  summarise(meanDischarge = mean(Discharge),
            sdDischarge = sd(Discharge),
            minDischarge = min(Discharge),
            maxDischarge = max(Discharge))


Club.Gorman_Flow_YearSummary <- Club.Gorman_Flow_Long %>% 
  mutate(year = year(Date)) %>% 
  group_by(site_no, year) %>% 
  filter(!is.na(Discharge)) %>% 
  summarise(meanDischarge = mean(Discharge),
            sdDischarge = sd(Discharge),
            minDischarge = min(Discharge),
            maxDischarge = max(Discharge))
```

# Nutrient Summaries
```{r}
EC_Nutrient_MonthSummary <- EC_Flow.Nutrients_Wide %>% 
  mutate(month = month(Date, label = TRUE)) %>% 
  group_by(month) %>% 
  filter(!is.na(Mixed_N), !is.na(TP)) %>% 
  summarise(meanN = mean(Mixed_N),
            sdN = sd(Mixed_N),
            minN = min(Mixed_N),
            maxN = max(Mixed_N),
            meanP = mean(TP),
            sdP = sd(TP),
            minP = min(TP),
            maxP = max(TP))

ggplot(EC_Nutrient_MonthSummary)+
  geom_point(aes(y = meanN, x=month))

ggplot(EC_Nutrient_MonthSummary)+
  geom_point(aes(y = meanP, x=month))

EC_Nutrient_YearSummary <- EC_Flow.Nutrients_Wide %>% 
  mutate(year = year(Date)) %>% 
  group_by(year) %>% 
  filter(!is.na(Mixed_N), !is.na(TP)) %>% 
  summarise(meanN = mean(Mixed_N),
            sdN = sd(Mixed_N),
            minN = min(Mixed_N),
            maxN = max(Mixed_N),
            meanP = mean(TP),
            sdP = sd(TP),
            minP = min(TP),
            maxP = max(TP))

ggplot(EC_Nutrient_YearSummary)+
  geom_point(aes(y = meanN, x=year))

ggplot(EC_Nutrient_YearSummary)+
  geom_point(aes(y = meanP, x=year))


```


# Flow 
```{r}
Dischargeplot <-
  ggplot(Club.Gorman_Flow_Long, aes(y = Discharge)) +
  geom_boxplot()
print(Dischargeplot)

mean(Club.Gorman_Flow_Long$Discharge, na.rm=TRUE)
min(Club.Gorman_Flow_Long$Discharge, na.rm=TRUE)
max(Club.Gorman_Flow_Long$Discharge, na.rm=TRUE)
sd(Club.Gorman_Flow_Long$Discharge, na.rm=TRUE)
IQR(Club.Gorman_Flow_Long$Discharge, na.rm=TRUE)

# Mean Annual Discharge 
MeanDischargeplot <-
  ggplot(Club.Gorman_Flow_YearSummary, aes(x = as.factor(year), y = meanDischarge, color = site_no)) +
  geom_point()+
  geom_smooth(method='lm')
print(MeanDischargeplot)

MeanMonthDischarge <- 
   ggplot(Club.Gorman_Flow_MonthSummary, aes(x = month, y = meanDischarge, color = site_no)) +
  geom_point()
print(MeanMonthDischarge)

MAxMonthDischarge <- 
   ggplot(Club.Gorman_Flow_MonthSummary, aes(x = month, y = maxDischarge, color = site_no)) +
  geom_point()
print(MAxMonthDischarge)


MaxYearDischarge <-
   ggplot(Club.Gorman_Flow_YearSummary, aes(x = year, y = maxDischarge, color = site_no)) +
  geom_point()
print(MaxYearDischarge)


DischargeTimeplot <-
  ggplot(Club.Gorman_Flow_Long, 
         aes(x = Date, y = Discharge, color = site_no))+
  geom_point() 
print(DischargeTimeplot)

DischargePlot <- 
  ggplot(Club.Gorman_Flow_Long, aes(x = Date, y = Discharge, color = site_no)) +
  geom_line() +
  ggtitle("Ellerbe Creek") +
  labs(x = "Time", y = expression("Discharge (ft"^3*"/s)")) + 
  theme(plot.title = element_text(margin = margin(b = -10), size = 12), 
        axis.text.x = element_blank(), axis.title.x = element_blank())
print(DischargePlot)

ClubDischargePlot <- 
  ggplot(Club.Gorman_Flow_Wide, aes(x = Date, y = Discharge.C)) +
  geom_line() +
  ggtitle("Club") +
  labs(x = "Time", y = expression("Discharge (ft"^3*"/s)")) + 
  theme(plot.title = element_text(margin = margin(b = -10), size = 12), 
        axis.text.x = element_blank(), axis.title.x = element_blank())
print(ClubDischargePlot)

ClubDischargePlot <- 
  ggplot(Club.Gorman_Flow_Wide, aes(x = Date, y = Discharge.G)) +
  geom_line() +
  ggtitle("Gorman") +
  labs(x = "Time", y = expression("Discharge (ft"^3*"/s)")) + 
  theme(plot.title = element_text(margin = margin(b = -10), size = 12), 
        axis.text.x = element_blank(), axis.title.x = element_blank())
print(ClubDischargePlot)

```



# Explore Nutrients with ggplot 
```{r}
### Phosphorus 

Pboxplot <-
  ggplot(EC_Flow.Nutrients_Wide, aes(x = HydrologicEvent, y = TP)) +
  geom_boxplot()
print(Pboxplot)


Discharge_TP <-
  ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = TP, y = Discharge.C, color = HydrologicEvent))+
  xlim(0,400)+
  ylim(0,400)+
  geom_point() 
print(Discharge_TP)

# Log 

logDischarge_logTP <-
  ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = log(TP), y = log(Discharge.C), color = HydrologicEvent))+
  geom_point()
print(logDischarge_logTP)
      

ClubGorman_Discharge_TP <-
  ggplot(Club.Gorman_Flow.Nutrients_Wide, 
         aes(x = TP, y = Discharge, color = HydrologicEvent))+
   xlim(0,400)+
  geom_point() 
print(ClubGorman_Discharge_TP)

Discharge_TN <-ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = Inorganic_N, y =Discharge.G, color = HydrologicEvent))+
  geom_point()+
  geom_smooth()
print(Discharge_TN)

Discharge_TN <-ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = Inorganic_N, y =Discharge.G))+
  geom_point()+
  geom_smooth()
print(Discharge_TN)

#Log Nitrogen

logDischarge_logTN <-ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = log(Inorganic_N), y =log(Discharge.G)))+
  geom_point()+
  geom_smooth(method='lm')
print(logDischarge_logTN)


Discharge_Turbidity <-
  ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = Turbidity, y = log(Discharge.G), color = HydrologicEvent))+
  geom_point()+
  geom_smooth(method = 'lm')
print(Discharge_Turbidity)

Discharge_XY <-
  ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = X_00060_00003.x, y = X_00060_00003.y, color = HydrologicEvent))+
  geom_point() 
print(Discharge_XY)

TP_TN <- 
   ggplot(EC_Flow.Nutrients_Wide, 
         aes(x = Mixed_N, y = TP, color = site_no))+
  geom_point()
print(TP_TN)

```

#Discharge vs Gage
```{r}
DvsGHplot <-
  ggplot(Club.Gorman_Flow_Long, aes(x = Discharge, y = Gage.Height, color=Date, shape = site_no)) +
  geom_point(alpha = 0.75)
print(DvsGHplot)

class(Club.Gorman_Flow_Long$Date)
```

# Seasonal Trend 

```{r}
Ellerbe.Historical <- mutate(Club.Gorman_Flow_Long, 
                                         DOY = yday(Date))

EllerbeDischarge.Pattern <- Ellerbe.Historical %>%
  group_by(DOY) %>%
  summarise(Median.Discharge = median(Discharge), 
            Max.Discharge = max(Discharge),
            Min.Discharge = min(Discharge))

EllerbePatternPlot <- 
  ggplot(EllerbeDischarge.Pattern, aes(x = DOY)) +
  geom_line(aes(y = Median.Discharge)) +
  geom_line(aes(y = Max.Discharge), color = "gray") +
  geom_line(aes(y = Min.Discharge), color = "gray") +  
  labs(x = "Day of Year", y = expression("Discharge (ft"^3*"/s)")) 
print(EllerbePatternPlot)

### Just Gorman 
Gorman.Historical <- mutate(Club.Gorman_Flow_Wide, 
                                         DOY = yday(Date))

GormanDischarge.Pattern <- Gorman.Historical %>%
  group_by(DOY) %>%
  summarise(Median.Discharge = median(Discharge.G), 
            Max.Discharge = max(Discharge.G),
            Min.Discharge = min(Discharge.G))

GormanPatternPlot <- 
  ggplot(GormanDischarge.Pattern, aes(x = DOY)) +
  geom_line(aes(y = Median.Discharge)) +
  geom_line(aes(y = Max.Discharge), color = "gray") +
  geom_line(aes(y = Min.Discharge), color = "gray") +  
  labs(x = "Day of Year", y = expression("Discharge (ft"^3*"/s)")) 
print(GormanPatternPlot)

# Just Club 
Club.Historical <- mutate(Club.Gorman_Flow_Wide, 
                                         DOY = yday(Date))

class(Club.Historical$Discharge.C)
median(Club.Historical$Discharge.C, na.rm=TRUE)

ClubDischarge.Pattern <- Club.Historical %>%
  group_by(DOY) %>%
  summarise(Median.Discharge = median(Discharge.C,na.rm=TRUE), 
            Max.Discharge = max(Discharge.C, na.rm=TRUE),
            Min.Discharge = min(Discharge.C), na.rm=TRUE)

ClubPatternPlot <- 
  ggplot(ClubDischarge.Pattern, aes(x = DOY)) +
  geom_line(aes(y = Median.Discharge)) +
  geom_line(aes(y = Max.Discharge), color = "gray") +
  geom_line(aes(y = Min.Discharge), color = "gray") +  
  labs(x = "Day of Year", y = expression("Discharge (ft"^3*"/s)")) 
print(ClubPatternPlot)
```
# Data Visualization Plot 

```{r}

### With Caption 
NPplot <-
  ggplot(Club.Gorman_Flow.NP_Long, aes(x= CharacteristicName, y = ResultMeasureValue, color = Location)) +
  geom_boxplot()+
  labs(x = "Nutrient", y = "Concentration (mg/L)", color = "", caption = "Kathleen is a superstar")+
  theme(plot.title = element_text(hjust = 0.5, face = "bold"), plot.caption = element_text(hjust = 0.5))+
scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(NPplot)

####
NPplot <-
  ggplot(Club.Gorman_Flow.NP_Long, aes(x= CharacteristicName, y = ResultMeasureValue, color = Location)) +
  geom_boxplot()+
  labs(x = "Nutrient", y = "Concentration (mg/L)", color = "")+
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))+
scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(NPplot)

Flowplot <-
  ggplot(Club.Gorman_Flow.Nutrients_Long, aes(x= "", y = Discharge, color = Location)) +
  geom_boxplot(show.legend = FALSE)+
  labs(x = "", y = (expression(paste("Discharge"  (ft^3/s)))), color = "")+
  theme(plot.caption = element_text(hjust = 0.5, size = 11))+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(Flowplot)

plot_grid(NPplot, Flowplot, nrow = 2, align = "v", rel_heights = c(2,1))



TPMonth_boxplot <-
ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = month, y = TP, color = Location))+ 
  geom_boxplot(show.legend = FALSE)+
  labs(x = "Month", y = "Phosphorus (mg/L)", color = "")+
  xlim("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(TPMonth_boxplot)

TNMonth_boxplot <- ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = month, y = Mixed_N, color = Location))+ 
  geom_boxplot(show.legend = FALSE)+
  labs(x = "Month", y ="Nitrogen (mg/L)", color = "")+
  xlim("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(TNMonth_boxplot)

plot_row1 <- plot_grid(NPplot, Flowplot, labels = c('A', 'B'))
plot_row2 <- plot_grid(TNMonth_boxplot,TPMonth_boxplot, labels = c('C', 'D'))

# now add the title
title <- ggdraw() + 
  draw_label(
    "Nutrient Concentrations and Flow at Upstream and Downstream Locations along Ellerbe Creek",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

title2 <- ggdraw() + 
  draw_label(
    "A. Boxplot of Nitrogen and phosphorus concentrations at upstream and downstream monitoring sites on ELlerbe Creek in North Carolina. B. Boxplot of flow at upstream and downstream monitoring sites on ELlerbe Creek. C. and D. Boxplot of monthly nitrogen and phosphorus concentrations at upstream and downstream monitoring sites on ELlerbe Creek.",
    fontface = 'italic',
    x = 0,
    hjust = 0, size = 11
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )


plot_grid(
  title, plot_row1, plot_row2, title2,
  ncol = 1,
  rel_heights = c(0.1, 1, 0.5)
)

plot_grid(NPplot, Flowplot, TNMonth_boxplot, TPMonth_boxplot, nrow = 2, align = "v", rel_heights = c(2,1), labels = c('A', 'B', 'C', 'D'))

```


# Nutrients near Club vs. Gorman
```{r}

Club.Gorman_Flow.NP_Long <- subset(Club.Gorman_Flow.Nutrients_Long,  CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)"| CharacteristicName == "Phosphorus")

class(Club.Gorman_Flow.NP_Long$CharacteristicName)
Club.Gorman_Flow.NP_Long$CharacteristicName <- as.character(Club.Gorman_Flow.NP_Long$CharacteristicName)

Club.Gorman_Flow.NP_Long$CharacteristicName[Club.Gorman_Flow.NP_Long$CharacteristicName =="Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)"] <- "Nitrogen"

#################
### Box Plots ###
#################

library("viridis")

NPplot <-
  ggplot(Club.Gorman_Flow.NP_Long, aes(x= CharacteristicName, y = ResultMeasureValue, color = Location)) +
  geom_boxplot()+
  labs(x = "Nutrient", y = "Concentration (mg/L)", color = "")+
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))+
scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(NPplot)

Flowplot <-
  ggplot(Club.Gorman_Flow.Nutrients_Long, aes(x= "", y = Discharge, color = Location)) +
  geom_boxplot(show.legend = FALSE)+
  labs(x = "", y = (expression(paste("Discharge"  (ft^3/s)))), color = "")+
  theme(plot.caption = element_text(hjust = 0.5, size = 11))+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(Flowplot)

plot_grid(NPplot, Flowplot, nrow = 2, align = "v", rel_heights = c(2,1))

TPMonth_boxplot <-
ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = month, y = TP, color = Location))+ 
  geom_boxplot(show.legend = FALSE)+
  labs(x = "Month", y = "Phosphorus (mg/L)", color = "")+
   xlim("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(TPMonth_boxplot)

TNMonth_boxplot <- ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = month, y = Mixed_N, color = Location))+ 
  geom_boxplot(show.legend = FALSE)+
  labs(x = "Month", y ="Nitrogen (mg/L)", color = "")+
   xlim("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(TNMonth_boxplot)


plot_row1 <- plot_grid(NPplot, Flowplot, labels = c('a.', 'b.'))
plot_row2 <- plot_grid(TNMonth_boxplot,TPMonth_boxplot, labels = c('c.', 'd.'))

# now add the title
title <- ggdraw() + 
  draw_label(
    "Nutrient Concentrations and Flow at Upstream and Downstream Locations along Ellerbe Creek",
    fontface = 'bold',
    size = 14,
    hjust = 0.5
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

title2 <- ggdraw() + 
  draw_label(
    "Figure 1. Distributions of nutrient concentrations and flow at upstream and downstream monitoring sites along Ellerbe Creek in North Carolina. \na) Nitrogen and phosphorus concentrations at upstream and downstream monitoring sites. b) Flow at upstream and downstream monitoring sites. \nc) and d) Monthly distributions of nitrogen and phosphorus concentrations at upstream and downstream monitoring sites.",
    hjust = 0.5, size = 11
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

plot_grid(
  title, plot_row1, plot_row2, title2,
  ncol = 1,
  rel_heights = c(0.1, 1, 0.5)
)

plot_grid(NPplot, Flowplot, TNMonth_boxplot, TPMonth_boxplot, nrow = 2, align = "v", rel_heights = c(2,1), labels = c('a', 'b', 'c', 'd'))

Gageplot <-
  ggplot(Club.Gorman_Flow.Nutrients_Long, aes(x= "", y = Gage.Height, fill = Location, color = Location)) +
  geom_boxplot()
print(Gageplot)

#################
###   N vs P  ###
#################
NvPplotUpstream <- ggplot(subset(Club.Gorman_Flow.Nutrients_Wide, Location == "Upstream"), aes(x = Mixed_N, y = TP)) +
  geom_point()
print(NvPplotUpstream)

NvPplotDownstream <- ggplot(subset(Club.Gorman_Flow.Nutrients_Wide, Location == "Downstream"), aes(x = Mixed_N, y = TP)) +
  geom_point()
print(NvPplotDownstream)

ggplot(EC_Flow.Nutrients_Wide, aes(x=Nitrate, y= Inorganic_N))+
  geom_point()

NvsP <-
ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = TP, y = Mixed_N, color = Location))+
  geom_point()+
  geom_smooth(method='lm')
print(NvsP)

NutrientMonth_boxplot <-
ggplot(Club.Gorman_Flow.NP_Long, aes(x = month, y = ResultMeasureValue, color = Location, fill = CharacteristicName))+ geom_boxplot()+
  labs(x = "Month", y = expression("Phosphorus" ~ (mu*g / L)), color = "")+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(NutrientMonth_boxplot)

TPMonth_boxplot <-
ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = month, y = TP, color = Location))+ 
  geom_boxplot(show.legend = FALSE)+
  labs(x = "Month", y = "Phosphorus (mg/L)", color = "")+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(TPMonth_boxplot)

TNMonth_boxplot <- ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = month, y = Mixed_N, color = Location))+ 
  geom_boxplot(show.legend = FALSE)+
  labs(x = "Month", y ="Nitrogen (mg/L)", color = "")+
  scale_color_manual(values = c("#82FF33", "#33ADFF"))
print(TNMonth_boxplot)

plot_grid(NPplot, Flowplot, TNMonth_boxplot, TPMonth_boxplot, nrow = 2, align = "v", rel_heights = c(2,1), labels = c('A', 'B', 'C', 'D'))

#########################
### Flow vs Nutrients ###
#########################

### Nitrogen 

UpstreamNvQ <- ggplot(subset(Club.Gorman_Flow.Nutrients_Wide, Location == "Upstream"), aes(x = Discharge, y = Mixed_N)) +
  geom_point()
print(UpstreamNvQ)

DownstreamNvQ <- ggplot(subset(Club.Gorman_Flow.Nutrients_Wide, Location == "Downstream"), aes(x = Discharge, y = Mixed_N)) +
  geom_point()
print(DownstreamNvQ)

TotalNvQ <- ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = Discharge, y = Mixed_N, color = Location)) +
  geom_point()
print(TotalNvQ)

### Phosphorus 

UpstreamPvQ <- ggplot(subset(Club.Gorman_Flow.Nutrients_Wide, Location == "Upstream"), aes(x = Discharge, y = TP)) +
  geom_point()
print(UpstreamPvQ)

DownstreamPvQ <- ggplot(subset(Club.Gorman_Flow.Nutrients_Wide, Location == "Downstream"), aes(x = Discharge, y = TP)) +
  geom_point()
print(DownstreamPvQ)

TotalPvQ <- ggplot(Club.Gorman_Flow.Nutrients_Wide, aes(x = Discharge, y = TP, color = Location)) +
  geom_point()
print(TotalPvQ)
```

